# Generated by Django 6.1 on 2026-08-31 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='fulfillment_type',
            field=models.CharField(choices=[('SEAT', 'Deliver to Seat (+₹10)'), ('TAKEAWAY', 'Takeaway / Counter Pickup')], default='SEAT', max_length=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='quantity_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='core.theater'),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='unit_spec',
            field=models.CharField(blank=True, help_text='e.g. 500ml, 100g', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('ONLINE', 'Online Payment'), ('CASH', 'Cash on Delivery')], default='ONLINE', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DELIVERED', 'Delivered/Picked Up'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
