# Generated by Django 6.1 on 2026-09-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_unit_price_orderitem_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.CharField(choices=[('SNACKS', 'Snacks'), ('DRINKS', 'Drinks'), ('COMBOS', 'Combos')], default='SNACKS', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theater',
            name='opening_time',
            field=models.CharField(default='10:00 AM - 11:30 PM', max_length=50),
        ),
        migrations.AddField(
            model_name='theater',
            name='phone_number',
            field=models.CharField(default='0484 123 4567', max_length=20),
        ),
    ]
