# Generated by Django 6.1 on 2026-09-02 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fooditem_category_order_is_paid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='address',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='theater',
            name='phone_number',
        ),
    ]
